### ISSUE TITLE
How to add --insecure-registry flag at coreos boot time?

### ISSUE THREAD

**Issue by huikang** [coreos/coreos-vagrant#235]
Hi, 
I am using coreos through vagrant. The CoreOS version is
CoreOS stable (647.0.0)

I would like to add --insecure-registry to start docker daemon at system boot time so that I can connect to my private registry. 
I found this link (https://coreos.com/blog/docker-1-3-2-stable-channel/).

However, there is not such directory /etc/systemd/system/docker.service.d/ in my version of coreos. Any suggestion? Thanks.

- Hui

**Comment by efranford** [comment]
Hi @huikang, 
You can make a shell provisioner that runs something like the following (substitute $HOST for your server or set that variable):

```
sudo cp /usr/lib/systemd/system/docker.service /etc/systemd/system/
sudo sed -e $"/^ExecStart/ s/$/ --insecure-registry $HOST/" -i /etc/systemd/system/docker.service

sudo systemctl daemon-reload
sudo systemctl restart docker
```

Hope this helps!

**Comment by misakwa** [comment]
@huikang I added the following to my cloudinit config to get it to work.
```
units:
  - name: docker.service
    drop-ins:
      - name: 50-insecure-registry.conf
        content: |
          [Service]
          Environment='DOCKER_OPTS=--insecure-registry="10.0.1.0/24"'
    command: start
```
I'm using the current stable version 681.2.0.
